### ISSUE TITLE
W10 crash during batch process

### ISSUE THREAD

**Issue by agriggio** [artpixls/ART#10]
**[Original report](https://bitbucket.org/agriggio/art/issues/10) by Gaaned92 (Bitbucket: [Gaaned92](https://bitbucket.org/Gaaned92), GitHub: [Gaaned92](https://github.com/Gaaned92)).**

----------------------------------------

W10

> Version: 0.3-49-gddf2ea05e  
> Branch: master  
> Commit: ddf2ea05e  
> Commit date: 2019-12-28  
> Compiler: gcc 9.2.0  
> Processor: SSE4  
> System: Windows  
> Bit depth: 64 bits  
> Gtkmm: V3.24.2  
> Lensfun: V0.3.95.0  
> Exiv2: V0.27.2  
> Build type: release  
> Build flags:  -m64 -mwin32 -msse2 -mfpmath=sse -mthreads -Wno-aggressive-loop-optimizations -Wno-parentheses -std=c\+\+11 -mtune=generic -msse4 -Werror=unused-label -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas  -DNDEBUG  -O3 -ftree-vectorize  
> Link flags: -m64  -mthreads  -static-libgcc   -mtune=generic -msse4  -s  -O3  -fno-use-linker-plugin  
> OpenMP support: ON  
> MMAP support: ON

‌

Image and ARP file attached

Use snapshot3 and batch process

‌

Backtrace:

‌

```plaintext
(gdb) run
Starting program: D:\art\artinstall\master_release64\art-debug.exe
[New Thread 15088.0x371c]
[New Thread 15088.0x818]
[New Thread 15088.0xfb4]
[New Thread 15088.0xee4]
[New Thread 15088.0x1108]
[New Thread 15088.0x2f60]
[New Thread 15088.0x1388]
[New Thread 15088.0x31bc]
[New Thread 15088.0x2de4]
[New Thread 15088.0x1e10]
[New Thread 15088.0x2fe0]
[New Thread 15088.0xc08]
[New Thread 15088.0xb6c]
[New Thread 15088.0x372c]
[New Thread 15088.0x2d3c]
[Thread 15088.0x2d3c exited with code 0]
[New Thread 15088.0x24d4]
[New Thread 15088.0x29f0]
[New Thread 15088.0x2a24]
[New Thread 15088.0x1688]
[New Thread 15088.0x29dc]
[New Thread 15088.0x1a18]
[New Thread 15088.0x38e0]
[New Thread 15088.0x728]
[Thread 15088.0x24d4 exited with code 0]
[Thread 15088.0x29dc exited with code 0]
[Thread 15088.0x2a24 exited with code 0]
[Thread 15088.0x29f0 exited with code 0]
[Thread 15088.0x38e0 exited with code 0]
[Thread 15088.0x1688 exited with code 0]
[Thread 15088.0x1a18 exited with code 0]
[Thread 15088.0x728 exited with code 0]
warning: NPGetCaps 2
warning:   WNNC_NET_TYPE
warning: NPGetCaps 4
warning:   WNNC_USER
warning: NPGetCaps 6
warning:   WNC_CONNECTION
warning: NPGetCaps 13
warning:   default
warning: NPGetCaps 11
warning:   WNNC_ENUMERATION
warning: NPGetCaps 9
warning:   WNNC_ADMIN
warning: NPGetCaps 8
warning:   WNNC_DIALOG
warning: NPOpenEnum: dwScope 0x00000001, dwType 0x00000001, dwUsage 0x00000000, lpNetResource 0000000000000000
warning: NPOpenEnum: pCtx 0000000012F23BC0
warning: NPEnumResource: hEnum 0000000012F23BC0, lpcCount 000000000CC3D610, lpBuffer 0000000012F73040, lpBufferSize 000000000CC3D680.
warning: NPEnumResource: *lpcCount 0xfffffffe, *lpBufferSize 0x3f6c, pCtx->index 0
warning: NPEnumResource CurrentSesstionID:1
warning: NPEnumResource nbRead:0
warning: NPEnumResource: Entries returned 0, dwStatus 0x00000103
[New Thread 15088.0x3848]
warning: NPCloseEnum: hEnum 0000000012F23BC0
warning: NPCloseEnum: returns
[Thread 15088.0x3848 exited with code 0]
[New Thread 15088.0x1588]
[New Thread 15088.0x3118]
[New Thread 15088.0x3a6c]
[New Thread 15088.0x2344]
[New Thread 15088.0x3588]
[New Thread 15088.0x33a4]
[New Thread 15088.0x2580]
[New Thread 15088.0x3634]
[New Thread 15088.0x720]
[New Thread 15088.0x3698]
[New Thread 15088.0x2c64]
[New Thread 15088.0xb0c]
[New Thread 15088.0x15ec]
[New Thread 15088.0x313c]
[New Thread 15088.0x1a54]

Thread 33 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 15088.0x3634]
0x00000000006ba7d9 in LUT<float>::operator[]<float, float, void> (
    index=-nan(0x400000), this=0xb72fa0 <rtengine::Color::cachef>)
    at D:/ART/ARTSOURCE/ART/rtengine/LUT.h:437
437         T operator[](V index) const
(gdb) bt full
#0  0x00000000006ba7d9 in LUT<float>::operator[]<float, float, void> (
    index=-nan(0x400000), this=0xb72fa0 <rtengine::Color::cachef>)
    at D:/ART/ARTSOURCE/ART/rtengine/LUT.h:437
        idx = -2147483648
        diff = -nan(0x400000)
        p1 = <optimized out>
        p2 = <optimized out>
        idx = <optimized out>
        diff = <optimized out>
        p1 = <optimized out>
        p2 = <optimized out>
#1  rtengine::Color::computeXYZ2Lab (f=-nan(0x400000))
    at D:/ART/ARTSOURCE/ART/rtengine/color.cc:1417
No locals.
#2  rtengine::Color::XYZ2Lab(float __vector(4), float __vector(4), float __vector(4), float __vector(4)&, float __vector(4)&, float __vector(4)&) (X=...,
    Y=..., Z=..., L=..., a=..., b=...)
    at D:/ART/ARTSOURCE/ART/rtengine/color.cc:1577
        y = -nan(0x400000)
        fx = <optimized out>
        fz = <optimized out>
        x = -nan(0x400000)
        z = -nan(0x400000)
        fy = <optimized out>
        k = <optimized out>
        minvalfv = {0, 0, 0, 0}
        maxvalfv = {65535, 65535, 65535, 65535}
        c500v = {500, 500, 500, 500}
        c200v = {200, 200, 200, 200}
        maxMask = <optimized out>
        minMask = <optimized out>
#3  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

‌

**Comment by agriggio** [comment]
**Original comment by agriggio (Bitbucket: [agriggio](https://bitbucket.org/agriggio), GitHub: [agriggio](https://github.com/agriggio)).**

----------------------------------------

RL deconvolution: protect from the generation of NaN values

Fixes #10
