### ISSUE TITLE
crash with log encoding

### ISSUE THREAD

**Issue by agriggio** [artpixls/ART#15]
**[Original report](https://bitbucket.org/agriggio/art/issues/15) by Gaaned92 (Bitbucket: [Gaaned92](https://bitbucket.org/Gaaned92), GitHub: [Gaaned92](https://github.com/Gaaned92)).**

----------------------------------------

W10, ART1.0RC2

to reproduce:

-open the image

-apply vertical perspective correction, 

-apply log encoding

crash:

> LENSFUN:  
> camera: Nikon Corporation Nikon D5200  
> lens: Nikon Nikon AF-S DX Zoom-Nikkor 18-105mm f/3.5-5.6G ED VR  
> correction: distortion, vignetting, CA, autoscaling  
> \[New Thread 6244.0x19ec\]  
> \[New Thread 6244.0x1504\]  
> \[New Thread 6244.0x850\]  
> \[New Thread 6244.0x24b4\]  
> \[New Thread 6244.0x2c5c\]  
> \[New Thread 6244.0x1838\]  
> \[New Thread 6244.0x1534\]  
> AutoLog: min = 0.00108779, max = 0.947684, DR = 9.76686  
> gray boundaries: 0.05, 0.25  
> computed gray point from 97086 samples: 14.428  
> LENSFUN:  
> camera: Nikon Corporation Nikon D5200  
> lens: Nikon Nikon AF-S DX Zoom-Nikkor 18-105mm f/3.5-5.6G ED VR  
> correction: distortion, vignetting, CA, autoscaling
>
> Thread 190 received signal SIGSEGV, Segmentation fault.  
> \[Switching to Thread 6244.0x1504\]  
> 0x00000000006b977a in LUT<float>::operator\[\]<float, float, void> \(  
> index=-nan\(0x400000\), this=0xb6cfa0 rtengine::Color::cachef\)  
> at D:/ART/ARTSOURCE/ART/rtengine/LUT.h:437  
> 437 T operator\[\]\(V index\) const  
> \(gdb\) bt full  
> \#0 0x00000000006b977a in LUT<float>::operator\[\]<float, float, void> \(  
> index=-nan\(0x400000\), this=0xb6cfa0 rtengine::Color::cachef\)  
> at D:/ART/ARTSOURCE/ART/rtengine/LUT.h:437  
> idx = -2147483648  
> diff = -nan\(0x400000\)  
> p1 = <optimized out>  
> p2 = <optimized out>  
> \#1 rtengine::Color::computeXYZ2Lab \(f=-nan\(0x400000\)\)  
> at D:/ART/ARTSOURCE/ART/rtengine/color.cc:1417  
> No locals.  
> ~~#2~~ rtengine::Color::XYZ2Lab \(X=<optimized out>, Y=-nan\(0x400000\),  
> Z=<optimized out>, L=@0x28046640: -nan\(0x400000\),  
> a=@0x27ed3c60: -nan\(0x400000\), b=@0x281b9020: -nan\(0x400000\)\)  
> at D:/ART/ARTSOURCE/ART/rtengine/color.cc:1547  
> x = -nan\(0x400000\)  
> z = -nan\(0x400000\)  
> y = -nan\(0x400000\)  
> fx = <optimized out>  
> fy = <optimized out>  
> fz = <optimized out>  
> ~~#3~~ 0x0000000000715375 in rtengine::Imagefloat::rgb\_to\_lab \(  
> b=@0x281b9020: -nan\(0x400000\), a=@0x27ed3c60: -nan\(0x400000\),  
> L=@0x28046640: -nan\(0x400000\), x=752, y=<optimized out>, this=0x16dcd0c0\)  
> at D:/ART/ARTSOURCE/ART/rtengine/imagefloat.cc:871  
> X = -nan\(0x400000\)  
> Y = -nan\(0x400000\)  
> Z = -nan\(0x400000\)  
> X = <optimized out>  
> Y = <optimized out>  
> Z = <optimized out>  
> ~~#4~~ rtengine::Imagefloat::\_ZN8rtengine10Imagefloat10rgb\_to\_labEb.\_omp\_fn.0\(void\) \(\) at D:/ART/ARTSOURCE/ART/rtengine/imagefloat.cc:861  
> Rv = <optimized out>  
> Bv = <optimized out>  
> Lv = \{0, 0, 0, 0\}  
> bv = \{0, 0, 0, 0\}  
> x = 752  
> Gv = <optimized out>  
> av = \{0, 0, 0, 0\}  
> y = <optimized out>  
> this = 0x16dcd0c0  
> ~~#5~~ 0x000000006360eaa0 in ?? \(\)  
> from D:\\art\\artinstall\\master\_release64generic\\libgomp-1.dll  
> No symbol table info available.  
> ~~#6~~ 0x0000000064945092 in pthread\_create\_wrapper \(\)  
> from D:\\art\\artinstall\\master\_release64generic\\libwinpthread-1.dll  
> No symbol table info available.  
> ~~#7~~ 0x00007ffef119b04a in msvcrt!\_beginthreadex \(\)  
> from C:\\WINDOWS\\System32\\msvcrt.dll  
> No symbol table info available.  
> ~~#8~~ 0x00007ffef119b11c in msvcrt!\_endthreadex \(\)  
> from C:\\WINDOWS\\System32\\msvcrt.dll  
> No symbol table info available.  
> ~~#9~~ 0x00007ffef10b7bd4 in KERNEL32!BaseThreadInitThunk \(\)  
> from C:\\WINDOWS\\System32\\kernel32.dll  
> No symbol table info available.  
> ~~#10~~ 0x00007ffef12aced1 in ntdll!RtlUserThreadStart \(\)  
> from C:\\WINDOWS\\SYSTEM32\\ntdll.dll  
> No symbol table info available.  
> \#11 0x0000000000000000 in ?? \(\)  
> No symbol table info available.  
> Backtrace stopped: previous frame inner to this frame \(corrupt stack?\)  
> \(gdb\)

‌

‌

**Comment by agriggio** [comment]
**Original comment by agriggio (Bitbucket: [agriggio](https://bitbucket.org/agriggio), GitHub: [agriggio](https://github.com/agriggio)).**

----------------------------------------

logenc: fixed crash due to division by zero generating a NaN

Fixes #15
