### ISSUE TITLE
Lockable color picker freezes Art

### ISSUE THREAD

**Issue by agriggio** [artpixls/ART#204]
**[Original report](https://bitbucket.org/agriggio/art/issues/204) by Paul Matthijsse (Bitbucket: [Paul Matthijsse](https://bitbucket.org/Paul Matthijsse), ).**

----------------------------------------

Found a problem when activating the lockable color picker: Art freezes, no way to get back to the hand tool. Version 1.9.3.23. 

Not so in Art 1.9.3.17 in a virtual machine.

**Comment by agriggio** [comment]
**Original comment by Paul Matthijsse (Bitbucket: [Paul Matthijsse](https://bitbucket.org/Paul Matthijsse), ).**

----------------------------------------

Hello, here’s a backtrace from a debug build, perhaps this helps to understand what’s going on when I click the lockable color picker. 

\[Thread 0x7fffbdffb700 \(LWP 43189\) exited\]  
\[Thread 0x7fffd37fe700 \(LWP 43164\) exited\]

MyMutex already locked!  
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 1 "ART" received signal SIGTRAP, Trace/breakpoint trap.  
raise \(sig=<optimized out>\) at ../sysdeps/unix/sysv/linux/raise.c:50  
50	../sysdeps/unix/sysv/linux/raise.c: Bestand of map bestaat niet.  
\(gdb\) backtrace  
\#0  raise \(sig=<optimized out>\) at ../sysdeps/unix/sysv/linux/raise.c:50  
\#1  0x00005555560b2b1a in MyMutex::checkLock\(\) \(this=0x555567f6e6e0\)  
at /home/paul/art/rtgui/threadutils.cc:38  
\#2  0x0000555555cb7108 in MyMutex::lock\(\) \(this=0x555567f6e6e0\)  
at /home/paul/art/rtgui/../rtengine/../rtgui/threadutils.h:165  
\#3  0x0000555555d04813 in MyMutex::MyLock::MyLock\(MyMutex&\)  
\(this=0x7fffffffd500, mutex=...\)  
at /home/paul/art/rtgui/../rtengine/../rtgui/threadutils.h:195  
\#4  0x0000555555d36d20 in CropHandler::colorPick\(rtengine::Coord const&, float&, float&, float&, float&, float&, float&, LockableColorPicker::Size\)  
\(this=0x555567f6e5d8, pickerPos=..., r=@0x7fffffffd58c: 0, g=@0x7fffffffd590: 0, b=@0x7fffffffd594: 0, rpreview=@0x7fffffffd598: 0, gpreview=@0x7fffffffd59c: 0, bpreview=@0x7fffffffd5a0: 0, size=LockableColorPicker::Size::S15\)  
at /home/paul/art/rtgui/crophandler.cc:580  
\#5  0x0000555555d46903 in CropWindow::updateHoveredPicker\(rtengine::Coord\*\)  
\(this=0x555567f6e400, imgPos=0x7fffffffd660\)  
at /home/paul/art/rtgui/cropwindow.cc:2241  
\#6  0x0000555555d3cdc9 in CropWindow::buttonPress\(int, int, int, int, int, double\)  
\(this=0x555567f6e400, button=1, type=4, bstate=20, x=343, y=155, pressure=0.0234832763671875\) at /home/paul/art/rtgui/cropwindow.cc:426  
\#7  0x0000555555f0c5de in ImageArea::on\_button\_press\_event\(\_GdkEventButton\*\)  
\(this=0x555565325bb0, event=0x555567e1b5e0\)  
--Type <RET> for more, q to quit, c to continue without paging--  
at /home/paul/art/rtgui/imagearea.cc:315  
\#8  0x00007ffff6ecbc79 in Gtk::Widget\_Class::button\_press\_event\_callback\(\_GtkWidget\*, \_GdkEventButton\*\) \(\) at /lib/x86\_64-linux-gnu/libgtkmm-3.0.so.1  
\#9  0x00007ffff7bc65ef in  \(\) at /lib/x86\_64-linux-gnu/libgtk-3.so.0  
\#10 0x00007ffff768ea56 in  \(\) at /lib/x86\_64-linux-gnu/libgobject-2.0.so.0  
\#11 0x00007ffff76acdf1 in g\_signal\_emit\_valist \(\)  
at /lib/x86\_64-linux-gnu/libgobject-2.0.so.0  
\#12 0x00007ffff76ae0f3 in g\_signal\_emit \(\)  
at /lib/x86\_64-linux-gnu/libgobject-2.0.so.0  
\#13 0x00007ffff7b70c23 in  \(\) at /lib/x86\_64-linux-gnu/libgtk-3.so.0  
\#14 0x00007ffff7a2c128 in  \(\) at /lib/x86\_64-linux-gnu/libgtk-3.so.0  
\#15 0x00007ffff7a2e3db in gtk\_main\_do\_event \(\)  
at /lib/x86\_64-linux-gnu/libgtk-3.so.0  
\#16 0x00007ffff7716f79 in  \(\) at /lib/x86\_64-linux-gnu/libgdk-3.so.0  
\#17 0x00007ffff774a106 in  \(\) at /lib/x86\_64-linux-gnu/libgdk-3.so.0  
\#18 0x00007ffff75a317d in g\_main\_context\_dispatch \(\)  
at /lib/x86\_64-linux-gnu/libglib-2.0.so.0  
\#19 0x00007ffff75a3400 in  \(\) at /lib/x86\_64-linux-gnu/libglib-2.0.so.0  
\#20 0x00007ffff75a34a3 in g\_main\_context\_iteration \(\)  
at /lib/x86\_64-linux-gnu/libglib-2.0.so.0  
\#21 0x00007ffff5083fe5 in g\_application\_run \(\)  
at /lib/x86\_64-linux-gnu/libgio-2.0.so.0  
\#22 0x0000555555f59bdb in main\(int, char\*\*\) \(argc=1, argv=0x7fffffffdf18\)  
--Type <RET> for more, q to quit, c to continue without paging--  
at /home/paul/art/rtgui/main.cc:570  
\(gdb\)

**Comment by agriggio** [comment]
**Original comment by agriggio (Bitbucket: [agriggio](https://bitbucket.org/agriggio), GitHub: [agriggio](https://github.com/agriggio)).**

----------------------------------------

crophandler: remove double (recursive) lock

Fixes #204

**Comment by agriggio** [comment]
**Original comment by Paul Matthijsse (Bitbucket: [Paul Matthijsse](https://bitbucket.org/Paul Matthijsse), ).**

----------------------------------------

Resolved indeed, thanks!
