### ISSUE TITLE
Crash when using Haldclut with sRGB working space

### ISSUE THREAD

**Issue by agriggio** [artpixls/ART#46]
**[Original report](https://bitbucket.org/agriggio/art/issues/46) by Gaaned92 (Bitbucket: [Gaaned92](https://bitbucket.org/Gaaned92), GitHub: [Gaaned92](https://github.com/Gaaned92)).**

----------------------------------------

Usually I use prophoto space. Doing some test with Haldclut, I stumbled upon this crash which happens only with sRGB working space

‌

> Program received signal SIGSEGV, Segmentation fault.  
> \[Switching to Thread 10468.0x2a9c\]  
> 0x00007ffae5984940 in msvcrt!memmove \(\) from C:\\WINDOWS\\System32\\msvcrt.dll  
> \(gdb\) bt full  
> \#0  0x00007ffae5984940 in msvcrt!memmove \(\) from C:\\WINDOWS\\System32\\msvcrt.dll  
> No symbol table info available.  
> \#1  0x00000000006d4ead in rtengine::HaldCLUTApplication::operator\(\) \(this=<optimized out>, r=0x1b791eb0, g=0x0,  
> b=0x0, istart=<optimized out>, istart@entry=0, jstart=<optimized out>, jstart@entry=672, tW=<optimized out>,  
> tH=<optimized out>, tH@entry=1\) at D:/ART/ARTSOURCE/ART/rtengine/clutstore.cc:441  
> i = 0  
> ti = 0  
> out\_rgbx = \{137773.125, -8.94602629e-032, -3.67385145e-038, 1.60990977e-040, nan\(0x583900\), -3.06935165e\+038,  
> -6.07053071e-031, -0.0001840638, 0, -nan\(0x7f2ae9\), -1050.28113, 1.60224793e\+019, 13.7659578,  
> 3\.18337507e\+014, -3.67939891e-038, 2.70097476e-040, -17993728, 439370.25, -4.4316162e-039, 9.04263504e-040,  
> 4\.71852836e-032, -4.86522827e\+029, 3.60288056e\+016, 1562.98022, 3.02673697, 2.60641514e-043,  
> -1.35956765e\+030, -4.03461161e\+029, 278.570282, -5.57259163e-029, 3.54248252e-042, 5.47634594e-017,  
> -1.29761135e-038, 2.78017615e-042, -9.42721317e\+024, -nan\(0x69f17f\), 7.11385173e-010, -1958380.75,  
> -5.11762624e-034, 3.58732407e-042, 1.03516734e-038, 2.396165e-029, -2.96982963e\+014, -2.40741831e-033,  
> 3\.69556804e-030, 5.35843641e\+036, 1.62735342e\+032, 3.13635314e\+017, -9.42602115e-036, -3.42026869e-005,  
> -nan\(0x7fffff\), 386.124512, 9.12888328e-038, -6.17386372e-031, 163985.438, 2.56717229, 3.68917335e-031,  
> -4.83015458e\+015, 3.68869187e-031, -3.01615332e\+038, 9.71284914e-030, 196878.844, -4.74730462e\+019,  
> 131072\.031, 1.39140219e-019, 5.74784382e-017, 1.04256606e-042, 8.83504164e-038, 6.44241084e-017,  
> 1\.03135567e-042, 6.64565797e-041, 9.7128499e-030, -6.18617256e-031, -nan\(0x7dec0d\), 2.24844467e-022,  
> -1.44830054e-030, 134701.125, 3.43395717e\+010, -nan\(0x7fb810\), 2.37644333e-029, -4.12200799e-037,  
> -3.01995294e-030, 134701.125, 3.43395717e\+010, 270168.75, -6.18651251e-031, -3.02499279e\+024,  
> 1\.93368678e-039, -8.21828735e\+024, 1.21287006e-039, -5.7020719e-029, -5.7020719e-029, -5.7020719e-029,  
> 9\.20592056e\+011, 4.00668298e-019, -7.95548716e-032, -8.36041869e\+018, -1.54135999e-033, 8.59892655e-023,  
> -17.1250248, -6.2407287e\+033, -68.6288986, 0.000397751137, -3.98079529e-012, 8, 101.341911, 8.06361103,  
> 0\.000124054219, -3.91525056e-015, 33554432, 3.76418372e\+021, -12.5645199, -2.58508456e-024, -2248.83008, 0,  
> -2.79871311e\+038, 4.19184791e-029, -1.78274105e\+021, -48107.0117, 0, -4.10253906, -46.3203278,  
> -3.8892844e-032, 8.91464044e-041, 3.27448645e-036, 1.42665618e-026, -1.24340142e\+010, 1.82808073e-038, 0,  
> 4\.52595459e-036, 5.27909936e\+032, -16.4106159, -4.97402839e\+010, -3.87656996e-032, 4.89683748e-041,  
> 3\.27448645e-036, 1.42665618e-026, -1.24340142e\+010, 1.82808073e-038, 0, 4.52595459e-036, 4.92415719e\+032,  
> ---Type <return> to continue, or q <return> to quit---  
> -5.11666366e-038, 2.69049305e-043, 3.98860294e-034, 1.88739489e-039, 5.27909936e\+032, 1247.36108,  
> 8\.08216572, 2.57838917e-043, -2.6306772e\+038, -5.90685866e-037, 3.94745895e\+018, -5.89989926e-037,  
> -3.85734592e-032, -4498560.5, -3.92925218e\+024, 8.65900135, -1.59202104e-033, 720.56665, 5.97716154e-010,  
> 4\.60864539e-017, 71975232, -5.67544981e-037, -6.16320904e-031, 10.0088692, 2.59240216e-043,  
> -2.13488238e-006, 8.70730983e-031, 5.2941056e-042, 4.74656343e-031, -5.89400214e-037, 24.4105301,  
> 1\.45860665e\+013, 216409.359, 172978.047, 4.9190137e\+015, 1.61203474e-023, -70144.1016, 4.73163748e-031,  
> -4.65918941e-033, -nan\(0x7799d8\), 24.0670185, -4.98802729e\+010, 1.35500615e-038, 9.51563467e-030,  
> -6.00224296e-031, -5.94835688e-031, -1.24151603e\+010, 1.30912427e-038, -3.77482269e-032, -3.85249407e-032,  
> 311873\.938, 1.81104444e-038, 8, 133858408, 2.65207645e-038, 1.34450117e-036, -2.62591347e\+038,  
> -8.1133504e-036...\}  
> clutr = \{0, 0, 0, 0, -0.00132703932, -0.00132703932, 0 <repeats 14 times>, -0.00132703932 <repeats 16 times>,  
> 1\.12103877e-044, 2.80259693e-045, 1.40129846e-045, 0, -nan\(0x7fffff\), 0, 0, 0, -0.00132703932,  
> -0.00132703932, -0.00132703932, -0.00132703932, 0, 0, 1.76778514e-021, 0, 1.70050542e-022, 0,  
> 1\.71168529e-022, 0, 1.62149614e-021, 0, 2.06083992e-022, 0, 1.50600691e-022, 0, 1.76921816e-021, 0,  
> 9\.26245992e-022, 0, -1.21979282e-012, -1.21979282e-012, -1.21979282e-012, -1.21979282e-012,  
> -1.58839967e\+038, -1.58839967e\+038, -1.58839967e\+038, -1.58839967e\+038, 0, 0, 0, 0, 8.96831017e-044, 0,  
> -9.93819561e-036, 0.0236534849, 2.75632493e\+023, 1.85168689e\+028, 2.45356199e\+029, 9.02903419e-010,  
> 5\.25334463e-039, -1.21979282e-012, -1.21979282e-012, -1.21979282e-012, -1.21979282e-012, -1.58839967e\+038,  
> -1.58839967e\+038, -1.58839967e\+038, 0, 0, 0, 0, -1.58839967e\+038, -1.58839967e\+038, -3.97527738e-035,  
> 1\.51380312, 2.75632493e\+023, 1.85168689e\+028, 2.45356199e\+029, 9.02903419e-010, 8.92676447e-039,  
> -1.21979282e-012, -1.21979282e-012, -1.21979282e-012, -1.21979282e-012, -1.58839967e\+038\}  
> clutg = <optimized out>  
> clutb = \{10272.6064, 9556.73633, 7816.29004, 5820.04834, 4154.52979, 3075.51343, 2343.40991, 1770.4137,  
> 1457\.04443, 1544.08069, 1531.50134, 1547.81897, 1642.88269, 1736.41968, 1591.13672, 1671.51099, 1358.2677,  
> 1256\.52271, 1456.81458, 1889.09607, 2125.81079, 2441.35815, 2925.49854, 3204.84497, 4062.15723, 4724.07471,  
> 5031\.03809, 5424.25049, 6715.99951, 9842.56934, 12361.7646, 15700.959, 19520.6094, 22775.6094, 25378.0762,  
> 25410\.9961, 24241.3242, 20465.9707, 16064.1904, 12224.1826, 9533.87012, 8433.21191, 7860.95801, 8701.61719,  
> 9158\.47363, 7756.68359, 5691.92969, 4166.55859, 4734.44727, 7434.27344, 12373.1699, 17673.1953, 20443.0645,  
> 19887\.6621, 17890.4922, 15775.5039, 13068.0889, 11465.3721, 11103.5088, 13403.9023, 16106.9434, 18103.8711,  
> ---Type <return> to continue, or q <return> to quit---  
> 20940\.293, 21275.5371, 20273.4766, 16781.5547, 13513.8262, 10101.5332, 7140.20068, 6775.35254, 6483.48779,  
> 6273\.03027, 6246.50928, 6268.88428, 6355.46143, 6481.53906, 6629.94287, 6633.47559, 6689.64844, 6557.03271,  
> 6648\.06543, 6682.06201, 6401.52734, 5511.19482, 3967.18823, 2807.97192, 2411.86084, 3029.16064, 4025.4292,  
> 5429\.82568, 6.27781712e-043, 0, 0, 0, 1.00352798e-038, 0, 3923.45874, 4829.08105, 5580.8291, 6461.08105,  
> 7552\.46826, 8442.08203, 9514.0127, 10561.8652, 11151.6318, 11093.2061, 11048.2715, 10774.1123, 9920.88477,  
> 9264\.2627, 8814.07129, 9052.22168\}  
> \#2  0x000000000083530b in rtengine::ImProcFunctions::_ZN8rtengine15ImProcFunctions14filmSimulationEPNS\_10ImagefloatE.omp\_fn.0\(void\) \(\) at D:/ART/ARTSOURCE/ART/rtengine/ipfilmsim.cc:51_  
> _jstart = 672_  
> _g = <optimized out>_  
> _r = <optimized out>_  
> _b = <optimized out>_  
> _jj = 672_  
> _img = 0x1c53db60_  
> _hald\_clut = \{clut\_filename_ = \{static npos = 18446744073709551615, string = \{  
> static npos = 18446744073709551615,  
> \_M\_dataplus = \{<std::allocator<char>> = \{<\_\_gnu\_cxx::new\_allocator<char>> = \{<No data fields>\}, <No data fields>\}, \_M\_p = 0x1b3b6d00 "Color\\Kodak\\Kodak Ektachrome 100 VS.png"\}, \_M\_string\_length = 39, \{  
> _M\_local\_buf = "'\\000\\000\\000\\000\\000\\000\\000ÏV¡d\\000\\000\\000", M\_allocated\_capacity = 39\}\}\},_  
> _working\_profile_ = \{static npos = 18446744073709551615, string = \{static npos = 18446744073709551615,  
> \_M\_dataplus = \{<std::allocator<char>> = \{<\__gnu\_cxx::new\_allocator<char>> = \{<No data fields>\}, <No data fields>\}, M\_p = 0x1d61f3d0 "sRGB"\}, M\_string\_length = 4, \{M\_local\_buf = "sRGB\\000\\000\\000\\000ÓJ"d\\000\\000\\000",_  
> _M\_allocated\_capacity = 1111970419\}\}\}, ok_ = true, clut\_and\_working\_profiles\_are\_same = true,  
> TS = 112, strength = 1,  
> hald\_clut = \{<std::\_\_shared\_ptr<rtengine::HaldCLUT, \(\_\_gnu\_cxx::\_Lock\_policy\)2>> = \{<std::_shared\_ptr\_access<rtengine::HaldCLUT, \(gnu\_cxx::Lock\_policy\)2, false, false>> = \{<No data fields>\}, M\_ptr = 0x18c30950,_  
> _M\_refcount = \{M\_pi = 0x224997b0\}\}, <No data fields>\}, wprof_ = 0x1b4cf400, wiprof = 0x13455720,  
> xyz2clut = 0xc8, clut2xyz = 0xf5e53a0, v\_work2xyz = \{\{\{1.71246986e-022, 0, 1.54142831e-044, 0\}, \{  
> 5\.77760133e-008, 2.94412807e-041, 1.71246986e-022, 0\}, \{0, 0, 2.18910025e\+022, 0\}\}, \{\{0, 0,  
> ---Type <return> to continue, or q <return> to quit---  
> 1\.68155816e-044, 0\}, \{7.55346061e\+026, 0, 1.71246986e-022, 0\}, \{4.42682239e-027, 0, 2.49078517e-027,  
> 0\}\}, \{\{1.39737483e-041, 0, 1.71246986e-022, 0\}, \{2.49078517e-027, 0, 2.48754036e-027, 0\}, \{  
> 2\.49078517e-027, 0, 2.4907792e-027, 0\}\}\}, v\_xyz2clut = \{\{\{1.71246986e-022, 0, 2.4293763e\+022, 0\}, \{  
> 1\.71246986e-022, 0, 1.40129846e-045, 0\}, \{1.39737483e-041, 0, 2.35220239e\+022, 0\}\}, \{\{  
> 1\.71247288e-022, 0, 0, 0\}, \{1.71246986e-022, 0, 2.35053493e\+022, 0\}, \{1.69424603e-022, 0,  
> 7\.55346061e\+026, 0\}\}, \{\{1.69424603e-022, 0, 7.55346061e\+026, 0\}, \{2.48754036e-027, 0,  
> 2\.42940152e\+022, 0\}, \{1.69424603e-022, 0, 7.55346061e\+026, 0\}\}\}, v\_clut2xyz = \{\{\{4.95391398e-027, 0,  
> 1\.71246986e-022, 0\}, \{1.69424603e-022, 0, 7.55346061e\+026, 0\}, \{1.71246986e-022, 0, 2.35458367e\+022,  
> 0\}\}, \{\{0, 0, 2.18699527e\+022, 0\}, \{1.70914377e-022, 0, 4.95391706e-027, 0\}, \{1.70914377e-022, 0,  
> 2\.0643205e-022, 0\}\}, \{\{2.80259693e-043, 0, 1.44737018e-022, 0\}, \{1.70914377e-022, 0, 7.53048546e-039,  
> 0\}, \{0, 0, 0, 0\}\}\}, v\_xyz2work = \{\{\{0, 0, 0, 0\}, \{2.99057114e-021, 0, 1.05377645e-042,  
> 7\.03451829e-043\}, \{1.14825079e-023, 0, 1.70914377e-022, 0\}\}, \{\{2.99056649e-021, 0, 0, 0\}, \{  
> 1\.07483396e-022, 0, 7.00975792e-022, 0\}, \{1.20603173e-038, 0, 1.20603173e-038, 0\}\}, \{\{0, 0,  
> 6\.70676299e-039, 0\}, \{0, 0, 1.07483396e-022, 0\}, \{7.00975792e-022, 0, 1.16352278e-038, 0\}\}\}\}  
> \#3  0x000000006360eaa0 in omp\_in\_final \(\) from D:\\ART\\artinstall\\master\_release64generic\\libgomp-1.dll  
> No symbol table info available.  
> \#4  0x0000000064945092 in pthread\_create\_wrapper \(\) from D:\\ART\\artinstall\\master\_release64generic\\libwinpthread-1.dll  
> No symbol table info available.  
> \#5  0x00007ffae594b04a in msvcrt!\_beginthreadex \(\) from C:\\WINDOWS\\System32\\msvcrt.dll  
> No symbol table info available.  
> \#6  0x00007ffae594b11c in msvcrt!\_endthreadex \(\) from C:\\WINDOWS\\System32\\msvcrt.dll  
> No symbol table info available.  
> \#7  0x00007ffae5477bd4 in KERNEL32!BaseThreadInitThunk \(\) from C:\\WINDOWS\\System32\\kernel32.dll  
> No symbol table info available.  
> \#8  0x00007ffae706ced1 in ntdll!RtlUserThreadStart \(\) from C:\\WINDOWS\\SYSTEM32\\ntdll.dll  
> No symbol table info available.  
> \#9  0x0000000000000000 in ?? \(\)  
> No symbol table info available.  
> Backtrace stopped: previous frame inner to this frame \(corrupt stack?\)  
> \(gdb\)  
> \(gdb\)

‌

**Comment by agriggio** [comment]
**Original comment by agriggio (Bitbucket: [agriggio](https://bitbucket.org/agriggio), GitHub: [agriggio](https://github.com/agriggio)).**

----------------------------------------

I can’t reproduce on \(my\) Linux, unfortunately. I’ll try on windows when I have the chance

**Comment by agriggio** [comment]
**Original comment by Daniel Catalina (Bitbucket: [Daniel Catalina](https://bitbucket.org/Daniel Catalina), ).**

----------------------------------------

I just tried with Windows10 and cannot reproduce. But maybe I did not followed the same workflow. What I did was:

* open the file
* change the processing profile to Neutral
* in the ‘Color Tab’ in the ‘Color Management’ module I’ve set the Working Profile to sRGB
* in the ‘Special effects’ tab in the Film Simulation module I selected the simulation provided above and activated the module

@{5d7247ab081fdf0db6e8df39} is this the same as you do?

@{557058:8f81e5da-fb6c-492f-84df-652b548f6648} I noticed that it makes a difference if one first selects the simulation first and than activates the module or the other way around. If the you first activate the Film Simulation and afterwards select the film simulation you want to use, it can happen that the preview is not updated until you change the Strength. 

‌

**Comment by agriggio** [comment]
**Original comment by Gaaned92 (Bitbucket: [Gaaned92](https://bitbucket.org/Gaaned92), GitHub: [Gaaned92](https://github.com/Gaaned92)).**

----------------------------------------

@{5e7b5019da12670c395d1d10} 

It crashes with the same procedure as you. \(last version\)

Perhaps it is something in the build.

Where did you download your build? I will test with it.

**Comment by agriggio** [comment]
**Original comment by Daniel Catalina (Bitbucket: [Daniel Catalina](https://bitbucket.org/Daniel Catalina), ).**

----------------------------------------

@{5d7247ab081fdf0db6e8df39} I build it myself …

**Comment by agriggio** [comment]
**Original comment by agriggio (Bitbucket: [agriggio](https://bitbucket.org/agriggio), GitHub: [agriggio](https://github.com/agriggio)).**

----------------------------------------

is this still valid? I have never been able to reproduce…

**Comment by agriggio** [comment]
**Original comment by Gaaned92 (Bitbucket: [Gaaned92](https://bitbucket.org/Gaaned92), GitHub: [Gaaned92](https://github.com/Gaaned92)).**

----------------------------------------

@{557058:8f81e5da-fb6c-492f-84df-652b548f6648} 

It is still valid on my conf. But as it is a totally marginal use case and you cannot reproduce, I think you will use your time better on other problems or improvements. So I propose you close this issue until some other people eventually stumble on it.

**Comment by agriggio** [comment]
**Original comment by agriggio (Bitbucket: [agriggio](https://bitbucket.org/agriggio), GitHub: [agriggio](https://github.com/agriggio)).**

----------------------------------------

no problem, I’ll keep it open
